DROP TABLE IF EXISTS `apps_nationality`;

CREATE TABLE `apps_nationality` (
	`id` int(11) unsigned NOT NULL AUTO_INCREMENT,
	`country_nationality_lower` varchar(100) NOT NULL DEFAULT (null,
	`country_nationality` varchar(100) NOT NULL DEFAULT (null,
	PRIMARY KEY (`id`),
	KEY `cc` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

LOCK TABLES `app_countries` WRITE;
--
-- Dumping data for table `apps_nationality`
--

INSERT INTO `apps_nationality` (`id`, `country_nationality_lower`, `country_nationality`)
VALUES

  (null, 'afghan', 'Afghan'),
  (null, 'albanian', 'Albanian'),
  (null, 'algerian', 'Algerian'),
  (null, 'american', 'American'),
  (null, 'andorran', 'Andorran'),
  (null, 'angolan', 'Angolan'),
  (null, 'antiguans', 'Antiguans'),
  (null, 'argentinean', 'Argentinean'),
  (null, 'armenian', 'Armenian'),
  (null, 'australian', 'Australian'),
  (null, 'austrian', 'Austrian'),
  (null, 'azerbaijani', 'Azerbaijani'),
  (null, 'bahamian', 'Bahamian'),
  (null, 'bahraini', 'Bahraini'),
  (null, 'bangladeshi', 'Bangladeshi'),
  (null, 'barbadian', 'Barbadian'),
  (null, 'barbudans', 'Barbudans'),
  (null, 'batswana', 'Batswana'),
  (null, 'belarusian', 'Belarusian'),
  (null, 'belgian', 'Belgian'),
  (null, 'belizean', 'Belizean'),
  (null, 'beninese', 'Beninese'),
  (null, 'bhutanese', 'Bhutanese'),
  (null, 'bolivian', 'Bolivian'),
  (null, 'bosnian', 'Bosnian'),
  (null, 'brazilian', 'Brazilian'),
  (null, 'british', 'British'),
  (null, 'bruneian', 'Bruneian'),
  (null, 'bulgarian', 'Bulgarian'),
  (null, 'burkinabe', 'Burkinabe'),
  (null, 'burmese', 'Burmese'),
  (null, 'burundian', 'Burundian'),
  (null, 'cambodian', 'Cambodian'),
  (null, 'cameroonian', 'Cameroonian'),
  (null, 'canadian', 'Canadian'),
  (null, 'cape verdean', 'Cape Verdean'),
  (null, 'central african', 'Central African'),
  (null, 'chadian', 'Chadian'),
  (null, 'chilean', 'Chilean'),
  (null, 'chinese', 'Chinese'),
  (null, 'colombian', 'Colombian'),
  (null, 'comoran', 'Comoran'),
  (null, 'congolese', 'Congolese'),
  (null, 'costa rican', 'Costa Rican'),
  (null, 'croatian', 'Croatian'),
  (null, 'cuban', 'Cuban'),
  (null, 'cypriot', 'Cypriot'),
  (null, 'czech', 'Czech'),
  (null, 'danish', 'Danish'),
  (null, 'djibouti', 'Djibouti'),
  (null, 'dominican', 'Dominican'),
  (null, 'dutch', 'Dutch'),
  (null, 'east timorese', 'East Timorese'),
  (null, 'ecuadorean', 'Ecuadorean'),
  (null, 'egyptian', 'Egyptian'),
  (null, 'emirian', 'Emirian'),
  (null, 'equatorial guinean', 'Equatorial Guinean'),
  (null, 'eritrean', 'Eritrean'),
  (null, 'estonian', 'Estonian'),
  (null, 'ethiopian', 'Ethiopian'),
  (null, 'fijian', 'Fijian'),
  (null, 'filipino', 'Filipino'),
  (null, 'finnish', 'Finnish'),
  (null, 'french', 'French'),
  (null, 'gabonese', 'Gabonese'),
  (null, 'gambian', 'Gambian'),
  (null, 'georgian', 'Georgian'),
  (null, 'german', 'German'),
  (null, 'ghanaian', 'Ghanaian'),
  (null, 'greek', 'Greek'),
  (null, 'grenadian', 'Grenadian'),
  (null, 'guatemalan', 'Guatemalan'),
  (null, 'guinean-bissau', 'Guinean-Bissau'),
  (null, 'guinean', 'Guinean'),
  (null, 'guyanese', 'Guyanese'),
  (null, 'haitian', 'Haitian'),
  (null, 'herzegovinian', 'Herzegovinian'),
  (null, 'honduran', 'Honduran'),
  (null, 'hungarian', 'Hungarian'),
  (null, 'icelander', 'Icelander'),
  (null, 'indian', 'Indian'),
  (null, 'indonesian', 'Indonesian'),
  (null, 'iranian', 'Iranian'),
  (null, 'iraqi', 'Iraqi'),
  (null, 'irish', 'Irish'),
  (null, 'israeli', 'Israeli'),
  (null, 'italian', 'Italian'),
  (null, 'ivorian', 'Ivorian'),
  (null, 'jamaican', 'Jamaican'),
  (null, 'japanese', 'Japanese'),
  (null, 'jordanian', 'Jordanian'),
  (null, 'kazakhstani', 'Kazakhstani'),
  (null, 'kenyan', 'Kenyan'),
  (null, 'kittian and nevisian', 'Kittian and Nevisian'),
  (null, 'kuwaiti', 'Kuwaiti'),
  (null, 'kyrgyz', 'Kyrgyz'),
  (null, 'laotian', 'Laotian'),
  (null, 'latvian', 'Latvian'),
  (null, 'lebanese', 'Lebanese'),
  (null, 'liberian', 'Liberian'),
  (null, 'libyan', 'Libyan'),
  (null, 'liechtensteiner', 'Liechtensteiner'),
  (null, 'lithuanian', 'Lithuanian'),
  (null, 'luxembourger', 'Luxembourger'),
  (null, 'macedonian', 'Macedonian'),
  (null, 'malagasy', 'Malagasy'),
  (null, 'malawian', 'Malawian'),
  (null, 'malaysian', 'Malaysian'),
  (null, 'maldivan', 'Maldivan'),
  (null, 'malian', 'Malian'),
  (null, 'maltese', 'Maltese'),
  (null, 'marshallese', 'Marshallese'),
  (null, 'mauritanian', 'Mauritanian'),
  (null, 'mauritian', 'Mauritian'),
  (null, 'mexican', 'Mexican'),
  (null, 'micronesian', 'Micronesian'),
  (null, 'moldovan', 'Moldovan'),
  (null, 'monacan', 'Monacan'),
  (null, 'mongolian', 'Mongolian'),
  (null, 'moroccan', 'Moroccan'),
  (null, 'mosotho', 'Mosotho'),
  (null, 'motswana', 'Motswana'),
  (null, 'mozambican', 'Mozambican'),
  (null, 'namibian', 'Namibian'),
  (null, 'nauruan', 'Nauruan'),
  (null, 'nepalese', 'Nepalese'),
  (null, 'new zealander', 'New Zealander'),
  (null, 'ni-vanuatu', 'Ni-Vanuatu'),
  (null, 'nicaraguan', 'Nicaraguan'),
  (null, 'nigerien', 'Nigerien'),
  (null, 'north korean', 'North Korean'),
  (null, 'northern irish', 'Northern Irish'),
  (null, 'norwegian', 'Norwegian'),
  (null, 'omani', 'Omani'),
  (null, 'pakistani', 'Pakistani'),
  (null, 'palauan', 'Palauan'),
  (null, 'panamanian', 'Panamanian'),
  (null, 'papua new guinean', 'Papua New Guinean'),
  (null, 'paraguayan', 'Paraguayan'),
  (null, 'peruvian', 'Peruvian'),
  (null, 'polish', 'Polish'),
  (null, 'portuguese', 'Portuguese'),
  (null, 'qatari', 'Qatari'),
  (null, 'romanian', 'Romanian'),
  (null, 'russian', 'Russian'),
  (null, 'rwandan', 'Rwandan'),
  (null, 'saint lucian', 'Saint Lucian'),
  (null, 'salvadoran', 'Salvadoran'),
  (null, 'samoan', 'Samoan'),
  (null, 'san marinese', 'San Marinese'),
  (null, 'sao tomean', 'Sao Tomean'),
  (null, 'saudi', 'Saudi'),
  (null, 'scottish', 'Scottish'),
  (null, 'senegalese', 'Senegalese'),
  (null, 'serbian', 'Serbian'),
  (null, 'seychellois', 'Seychellois'),
  (null, 'sierra leonean', 'Sierra Leonean'),
  (null, 'singaporean', 'Singaporean'),
  (null, 'slovakian', 'Slovakian'),
  (null, 'slovenian', 'Slovenian'),
  (null, 'solomon islander', 'Solomon Islander'),
  (null, 'somali', 'Somali'),
  (null, 'south african', 'South African'),
  (null, 'south korean', 'South Korean'),
  (null, 'spanish', 'Spanish'),
  (null, 'sri lankan', 'Sri Lankan'),
  (null, 'sudanese', 'Sudanese'),
  (null, 'surinamer', 'Surinamer'),
  (null, 'swazi', 'Swazi'),
  (null, 'swedish', 'Swedish'),
  (null, 'swiss', 'Swiss'),
  (null, 'syrian', 'Syrian'),
  (null, 'taiwanese', 'Taiwanese'),
  (null, 'tajik', 'Tajik'),
  (null, 'tanzanian', 'Tanzanian'),
  (null, 'thai', 'Thai'),
  (null, 'togolese', 'Togolese'),
  (null, 'tongan', 'Tongan'),
  (null, 'trinidadian or tobagonian', 'Trinidadian or Tobagonian'),
  (null, 'tunisian', 'Tunisian'),
  (null, 'turkish', 'Turkish'),
  (null, 'tuvaluan', 'Tuvaluan'),
  (null, 'ugandan', 'Ugandan'),
  (null, 'ukrainian', 'Ukrainian'),
  (null, 'uruguayan', 'Uruguayan'),
  (null, 'uzbekistani', 'Uzbekistani'),
  (null, 'venezuelan', 'Venezuelan'),
  (null, 'vietnamese', 'Vietnamese'),
  (null, 'welsh', 'Welsh'),
  (null, 'yemenite', 'Yemenite'),
  (null, 'zambian', 'Zambian'),
  (null, 'zimbabwean', 'Zimbabwean'),
UNLOCK TABLES;
